version: '3'
services:
  db:
    image: "mysql:8.0"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - "./src:/app"
    command: python telegram_bot.py

volumes:
  db_data: {}