"""Added interval

Revision ID: 11cb3ad55bbb
Revises: 601f4eba286a
Create Date: 2021-12-24 13:23:44.267275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cb3ad55bbb'
down_revision = '601f4eba286a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interval')
    # ### end Alembic commands ###
