"""Changed PK

Revision ID: 28021f39ebb3
Revises: 4c782c3c5e3d
Create Date: 2021-12-24 00:50:31.528570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28021f39ebb3'
down_revision = '4c782c3c5e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='users')
    op.drop_column('users', 'telegram_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('user_id', 'users', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###
