"""Create all

Revision ID: 3c7e21e9ab84
Revises:
Create Date: 2021-12-23 14:53:13.740159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c712c3c4ed21'
down_revision = '3c7e21e9ab84'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('users', 'user_id', nullable=False, existing_type=sa.Integer, new_column_name='telegram_user_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_user_id', nullable=False, existing_type=sa.Integer, new_column_name='user_id')
    # ### end Alembic commands ###
