"""Unique together

Revision ID: 601f4eba286a
Revises: 28021f39ebb3
Create Date: 2021-12-24 00:54:16.644900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601f4eba286a'
down_revision = '28021f39ebb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_link_uc', 'resources', ['user_id', 'link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_link_uc', 'resources', type_='unique')
    # ### end Alembic commands ###
