"""Added apscheduler

Revision ID: d78604b7c570
Revises: 11cb3ad55bbb
Create Date: 2021-12-24 20:37:11.085852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd78604b7c570'
down_revision = '11cb3ad55bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_next_run_time'), 'apscheduler', ['next_run_time'], unique=False)
    op.drop_index('ix_tags_title', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('article_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='tags_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tags_title', 'tags', ['title'], unique=False)
    op.drop_index(op.f('ix_apscheduler_next_run_time'), table_name='apscheduler')
    op.drop_table('apscheduler')
    # ### end Alembic commands ###
